### ISSUE TITLE
Create github page for the project

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#11]
As the issue on the website was lost, I'll recap here the remaining task for the website:

**Tasks:**
- [ ] Add open graph meta tags
- [ ] Add addons page to list available addons on NPMs, filtered by a static json blacklist
- [ ] Add form (google forms?) to submit person/companies using the project
- [ ] Add blog tab that redirects to ngx rocket
- [ ] Use hashbang routing instead of HTML5 mode to fix F5 issues (to be replaced later by a proper NodeJS server acting as a reverse proxy?)

---
Old issue description:

- Setup a Jekyll template for github pages deployment
- Write some promotion/communication stuff about the goals and benefits

For the design, use these for inspiration: http://fountainjs.io, https://github.com/CloudCannon/cause-jekyll-template, https://github.com/CloudCannon/hydra-jekyll-template

The idea would be to have a nice 1-page website with scroll hooks and links to github/npm etc.

**Comment by sinedied** [comment]
@gaetanmaisse would you like to give it a go?

**Comment by gaetanmaisse** [comment]
@sinedied, I won't have enough time to work on it before a while... so I unassigne me this issue

**Comment by japf** [comment]
I'm playing a lot with [Hugo](http://gohugo.io/) lately. If you think that would be a good option I might work on this to have a landing page built with Hugo. The advantage of using Hugo is that we could also reuse the docs that are in Markdown in this repo to include them in the website.

Hugo supports a bunch of [themes](http://themes.gohugo.io/) and I think we should find that fits the need of the starter-kit. Some examples:

* [Universal](http://themes.gohugo.io/hugo-universal-theme/)

![image](https://cloud.githubusercontent.com/assets/2237018/23395926/6cb9fe40-fd91-11e6-881d-876d9e602292.png)

* [Hyde-Y](http://themes.gohugo.io/hyde-y/)

![image](https://cloud.githubusercontent.com/assets/2237018/23395975/9e7fc39c-fd91-11e6-933e-c726000940b2.png)

* [Elate](http://themes.gohugo.io/hugo-elate-theme/)

![image](https://cloud.githubusercontent.com/assets/2237018/23396020/d84f2ee6-fd91-11e6-936f-b42a31afda1b.png)

Let me know your thoughts :-)

**Comment by sinedied** [comment]
Seems like a great idea! 👍 

I was thinking of Jekyll because of the native Github integration, but Hugo would also be a good fit.

For the theme, I like the `Universal` you mentioned, and I also the simplicity of the [creative](http://themes.gohugo.io/creative/).
Any other opinion?

**Comment by japf** [comment]
For any options we will need to have a nice background image. 

@sinedied is there any chance you could take a nice screenshot of your dev environment when working on the starter-kit? Something with the IDE + plenty of code and cool dev stuff :-) Using bit of blur + transparency that should do the trick to have a background we can use in the teme.

**Comment by sinedied** [comment]
@japf I'll do this and post it here

**Comment by sinedied** [comment]
Would something like this do the job?
![ngx](https://cloud.githubusercontent.com/assets/593151/23523378/efd89cae-ff86-11e6-84cd-8f29d3c57e26.jpg)

With 40% black overlay:
![ngx-black40](https://cloud.githubusercontent.com/assets/593151/23523374/eb9c3ac4-ff86-11e6-8772-331fa0a7c31a.jpg)

I have higher-res (x2) images if needed.

**Comment by sinedied** [comment]
As the website is live since a while, I think it's time to close this one 😄
