### ISSUE TITLE
Allow to only generate the toolchain

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#144]
When running `ngx update` it is often desirable to only update the toolchain and dependencies but leave the app intact (as it was most likely modified).

A new `--only-tools` (or `-ot`) option should be added to use generate only the tooling part, whether using `new` or `update` command. This option could also be forced by an add-on, if one add-on wants to take care of the templating part (an info message should be issues in this case).

This would also be useful for other scenarios, like upgrading an existing non-ngX-Rocket project to use its toolchain.

To filter out unwanted files, a logic similar to a `.gitignore` file should be used using https://github.com/kaelzhang/node-ignore.

To also provide better control over which files to use from the main generator when using addons, a helper function should be provided by the core generator to allow filtering out any files from the main generator based on ignore patterns.

**Tasks:**
- [x] Implement `.toolsignore` file support in `@ngx-rocket/core`:
  * default filter is `*` to enable backward compatibility in addons
  * filter can be configured either by a `toolsFilter` array (fed to node-ignore add function) in `Generator.make` or by adding a `.toolsignore` file aside the `index.js` file of the generator
- [x] Add helper method to `@ngx-rocket/core` to filter any file from the main generator using ignore patters
- [x] add `--only-tools` / `-ot` option to `generator-ngx-rocket`: if enabled, the core should filter files automatically during generation
- [x] write doc in core to explain the usage, configuration and behavior
- [x] update officials add-ons with `.toolsignore`
- [x] update `generator-ngx-rocket-addon` and `addon-example` to include a default `.toolsignore` file with the default `*` filter and a comment to reference the doc
- [x] add tools, docs and dependency-related files to `.toolsignore` file
- [ ] (optional sugar) allow `package.json` file to be merged with existing one when running in update mode

**Comment by SpiraMira** [comment]
This seems related to my #175 . My particular use case is :

1 - ngx new a project
2 - add local features (not with add-ons)
3 - rocket updates the base template as maintenance (new version of Angular etc...). This affects things like core and the toolchain. There is a new release of generator-ngx-rocket.
4 - currently ngx-update will not pull new updates down.

Will this feature address this? Am I missing something?

I know this is a down side of generated project templates. The starter-kit seems to have multiple branches/feature sets. Is it maintained with ngx cli or manually?

Thanks.

**Comment by sinedied** [comment]
> 4 - currently `ngx update` will not pull new updates down.

When the new generator version is out, this will work.

Even without being able to generate only the toolchain, the update will work as I indicated in #175, but it will also overwrite templates files (which is not generally wanted) so you'll have to revert them.

This goal of this feature is to simplify the update workflow by keeping the "merging changes" task to a minimum.

As for the `starter-kit` repo, the `master` and `cordova/ionic` branches are generated automatically on new `generator-ngx-rocket` releases. The other branches are used either when working on new generator features or for bug reports demonstration on angular/ionic/etc.

**Comment by SpiraMira** [comment]
Got it. Thx.
