### ISSUE TITLE
Create codelabs

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#147]
I just saw https://codelabs.developers.google.com while searching for an open platform to create codelabs, and though that it would be great to create ngX-Rocket step-by-step codelabs.

Here are a few ideas:
- Create a PWA and deploy on firebase (cellar management example?)
- Create a mobile app
- Create a ngX-Rocket add-on

The tools seems very straightforward, as codelabs can be generated from simple markdown files with special format using this tool: https://github.com/googlecodelabs/tools/tree/master/claat

Here is the md format: https://github.com/googlecodelabs/tools/tree/master/claat/parser/md
An example setup: https://github.com/bobbijvoet/web-components-codelab

The result could be published on the website (see #11) and hosted using github pages.

**Tasks:**
- [ ] Init codelab repo with setup for multiple codelabs
- [ ] Create script to compile a codelab and deploy it on github pages
- [ ] Run the deployment script with Travis to make it automatic
- [ ] Create a first codelab 😄

**Comment by sinedied** [comment]
After a few (offline) discussions, it seems the most reasonable way to do this is using simple [Medium](https://medium.com) articles for the tutorials, and group them on a Medium blog that could be exposed on the website.

Simpler and more engaging for the writers & readers 😄

**Comment by reflexdemon** [comment]
Something on the similar lines. I had written a blog on writing a PWA and hosting in 15 minutes based upon this generator. If you guys like, I done mind sharing this https://blog.vpv.io/2018/03/pwa-building-and-publishing-pwa-in.html

**Comment by PI-Mathis** [comment]
Working on an Medium-article which describes this generator at the very moment.

**Comment by fethiissa** [comment]
> It seems the most reasonable way to do this is using simple [Medium](https://medium.com) articles for the tutorials, and group them on a Medium blog that could be exposed on the website.
> 
> Simpler and more engaging for the writers & readers 😄

Hey @sinedied, I am a Angular newbie who just discovered NgxRocket and fell in love with it. I totally agree with your statement above and would like to write simple tutorials to help myself and others understand this awesome tool.

However, I am stuck past initial project shell scaffolding. How do I leverage addons to build say, a movie rating CRUD app for instance? 

Thanks

**Comment by sinedied** [comment]
Thanks for the feedback @fethiissa , I'm glad you like it!

> How do I leverage addons to build say, a movie rating CRUD app for instance?
Do you want to create an add-on, or would like to use an existing add-on for creating a CRUD app?

For the 1), you can take a look at this [example](https://github.com/ngx-rocket/addon-example) and [these docs](https://github.com/ngx-rocket/core), if it's for 2) I'm not sure such an addon already exists for this, but it seems similar in idea to what [JHipster](https://github.com/ngx-rocket/core) is doing with its entity generator.
