### ISSUE TITLE
Add option flag to allow using existing Chrome install instead of puppeteer

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#171]
Since #128 we moved from PhantomJS to Chrome Headless, and used [puppeteer](https://github.com/GoogleChrome/puppeteer) for that to have a replicable version across environments.

Some people suggested to add an option to avoid downloading an extra Chrome binary, so here is the issue. Since it's not a common use case, I would rather avoid adding an extra question to the generator but instead using a flag for this.

**Tasks:**
- [x] add an `--external-chrome` option to the generator
- [x] update templates to exclude `puppeteer` and the extra Karma config when this flag is set
- [x] update generator doc with options flags

**Comment by zohon** [comment]
https://github.com/ngx-rocket/generator-ngx-rocket/pull/173
