### ISSUE TITLE
Merge addon generator as a subgenerator of ngx-rocket

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#176]
As an effort to simplify maintenance and usage of ngX-Rocket, it would be nice to merge https://github.com/ngx-rocket/generator-ngx-rocket-addon back into the main ngx-rocket generator, as a Yeoman `addon` subgenerator.

**Tasks**:
- [x] Migrate addon generator code as a subgenerator of ngx-rocket
- [x] Update CI to include addon generation
- [x] Add documentation about using the addon generator
- [x] Deprecate `generator-ngx-rocket-addon` on NPM and update doc on the repo to mention that it has moved
- [x] Update CLI to use the sub-generator
