### ISSUE TITLE
Update cordova/plugins and remove Crosswalk / enhanced webviews questions

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#180]
As cordova-android was bumped to `6.4.0` to work with the latest android build tools, Crosswalk support [was broken](https://cordova.apache.org/announcements/2017/11/09/android-release.html).
Unfortunately, since Crosswalk is not maintained anymore, it's unknown whether the issue will be fixed or not, so the solution for now would be to remove it entirely. EDIT: A solution may be coming: https://github.com/apache/cordova-android/pull/417

At the same time, the Ionic WKWebView is now considered stable and has move to its own repo: https://github.com/ionic-team/cordova-plugin-ionic-webview
All together, we think that it should now be always enabled (it was already the default) and the question whether to choose it or not should be removed entirely, as Crosswalk is removed.

**Tasks**:
- [x] Update cordova and plugins
- [x] Change Ionic WKWebView reference to point to the new repo
- [x] Remove Crosswalk
- [x] Remove Enhanced webview choice (keep Ionic WKWebView always enabled)
- [x] Update Cordova documentation and Readme to reflect the changes
- [x] **BREAKING CHANGE**: Remove `webview` from generator props
