### ISSUE TITLE
Merge CLI repo in main generator repo

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#184]
As a follow-up to #176, I think we should also merge the CLI within the main repo, again as an effort to simplify maintenance and usage of ngX-Rocket.

This would also reduce confusion about CLI vs generator usage, and generator version vs CLI version issues.

Having the CLI installed with generator directly would also mean that we can safely make it the main way to use the generator and remove the CLI vs Yeoman usage section.

**Tasks:**
- [x] Merge CLI code in the generator-ngx-rocket repo
- [x] Update CI to also test CLI
- [x] Update documentation to mention the CLI and update usage section
- [x] Update all CLI docs (within this repo and others like core, add-ons...)
- [ ] Deprecate `@ngx-rocket/cli` on NPM
- [x] Update CLI code to use register the generators directly (app and addon)
