### ISSUE TITLE
Improve login component to add sign up/lost password pages

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#186]
The current login page generated is a simple login/pass entry page to validate a basic auth workflow.

Once integrated with a real auth solution, most often it will be desirable to add signup and lost password page, so they should be generated as well and part of the login module.

**Tasks**
- [ ] Add signup page to the login module with minimum form input and validation (email, password) and ok/cancel buttons + button to access from login page [for Ionic, Bootstrap and Material]
- [ ] Add lost password page to the login module: email field + ok/cancel buttons + button to access from login page [for Ionic, Bootstrap and Material]
- [ ] Add mock methods to sign up / reset password to authentication service + unit tests
