### ISSUE TITLE
CI: Add visual regression tests

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#259]
To complete our CI suite, it would be interesting to add visual regression tests to reduce manual sanity checks with the different UIs.

If it works well it could also be considered for a direct integration in generated project as part of the testing suite.

So far for doing this I identified these tools that could be used, plugged to the existing e2e tests:
- https://github.com/mlison/protractor-jasmine2-screenshot-reporter: to generate screenshots for each test. We would have to improve a little the generated e2e tests to add a test for the login page when auth is used, to have a screenshot of this page.
- https://github.com/reg-viz/reg-suit: to compare 2 sets of screenshots on the CI and reports eventual errors.

We would also need to store the screenshots somewhere: either on a separate git branch that would be overwritten each time the suite is updated to avoid growing the repo too fast, or on another network storage (AWS S3, dropbox or anything suitable...). There is also the possibility with `reg-suit` to generate the screenshots in-place for 2 differents branches (master and the PR for example) to avoid the storage issue, but that would fail to detect regressions due to frameworks or tools update.

**Tasks:**
- [ ] Update generated e2e tests to test the login page when auth is enabled
- [ ] Update the `test.sh` script to trigger VR tests when the `TEST_VISUA` env variable is enabled
  * Add https://github.com/mlison/protractor-jasmine2-screenshot-reporter to generated project
  * Generate screenshots
  * Add an option to overwrite generated screenshots so they can be used a the new base for comparison
- [ ] Add a script `package.json` in the generator to update the base tests 
- [ ] Configure the CI to generate the screenshots
- [ ] Configure https://github.com/reg-viz/reg-suit to perform the comparison between the CI generated screenshots and the base ones
- [ ] Find a way to report nicely visual errors from the CI (investigate https://github.com/reg-viz/reg-suit solutions and tools)
