### ISSUE TITLE
i18n and language selection for projects

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#262]
In light of https://github.com/ngx-rocket/generator-ngx-rocket/pull/248, it would be nice to allow selecting the language you want to support in your projects via a toggle list, instead of forcing EN/FR by default.

Translations could be done by the community via https://crowdin.com (a request for open source has already be sent to them).

**Tasks:**
- [x] Initiate project on crowdin
- [x] Update generator templates
- [x] Add CLI prompts to select languages
- [ ] Add message for community help for translation in CLI prompt with crowdin link

**Comment by snowyu** [comment]
almost done here: https://github.com/snowyu/generator-ngx-rocket/tree/feature/%40core-%40shared

But I change the core module and shared module name to @core and @shared.

**Comment by sinedied** [comment]
@snowyu Maybe it's missing some infos in issue description, but the idea is to have a language selection during the project generation, not in the generated project itself :)

Maybe we could even allow disabling i18n completely for projects that do not need it, as it was requested previously.

**Comment by snowyu** [comment]
But not disable i18n completely yet.

use my branch `dev` or `feature/@core-@shared`:

```bash
          __   __
 _ _  __ _\ \./ / ____ ____ ____ _  _ ____ ___
| ' \/ _` |>   <  |--< [__] |___ |-:_ |===  |
|_||_\__, /_/°\_\ ENTERPRISE APP STARTER -~*=>
     |___/ v4.0.0

Using pre-commit-addon 1.0.1
? What's the name of your app? a
? What kind of app do you want to create? Web app
? Do you want a progressive web app? (with manifest and service worker) Yes
? Which UI framework do you want? Bootstrap (more website-oriented)
? Do you want authentication? Yes
? Do you want lazy loading? No
? Do you want language internationalization support? Yes
? Which languages do you want to support? (Press <space> to select, <a> to toggle all, <i> to inverse selection)
❯◉ en-US
 ◉ fr-FR
 ◉ zh-CN
? Which language are the default(fall back)? 
❯ en-US 
  fr-FR
  zh-CN 
 Shall we commit all files to local git? Yes
? What's the message of the commit? init
```

**Comment by sinedied** [comment]
Sorry I missed that one! I'll take a deeper look at it then, looks like what we would to achieve then 👍
