### ISSUE TITLE
Add --strict-mode option to enable TypeScript strict mode

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#292]
Since we support typescript strict mode compatibility, let's make it more official by providing a generator option to enable it, removing the need for a dedicated CI branch.

**Tasks**:
- [x]  Add `--strict-mode` option to the generator and update README to describe the option
- [x] Update the `tsconfig.json` template to enable strict mode if the option is set
- [x] Add CI test cases for strict mode (at least 1 for each UI branch)
