### ISSUE TITLE
Angular 6 support

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#301]
Next major version of Angular is around the corner, so we should prepare for it and update dependencies for it. I might take some times (as usual) before all dependencies supports it and makes it viable for a release.

**Tasks**
- [x] Update dependencies (do not forget https://github.com/ngx-translate/core @10)
- [x] Migrate to RxJS 6
- [x] Fix npm tasks
- [x] Migrate project files (`angular.json` and others)
- [ ] Update readme and docs (do not forget SK readme!)

**Blocking issues:**
- ~~https://github.com/angular/angular-cli/issues/10859 / https://github.com/angular/angular/issues/21049~~ => workaround with `preserveWhitespace: true` in `src/tsconfig.app.json`

**Comment by yacineblr** [comment]
ngx-translate support Angular 6 now ?
