### ISSUE TITLE
Add yarn option instead of npm

### ISSUE THREAD

**Issue by sinedied** [ngx-rocket/generator-ngx-rocket#49]
[yarn](https://yarnpkg.com/lang/en/) is an alternative to NPM, with (almost) only benefits:
- faster, with better caching support
- more dev-friendly (use `yarn test:ci` instead of `npm run test:ci` with no [silly noise](https://github.com/npm/npm/issues/8821)
- lock dependencies by default (like shrinkwrap)

It would be nice to add a generator option to use `yarn` instead of `npm`, while keeping `npm` as the default as it needs to extra package to install.

**Tasks**:
- [x] Update `@ngx-rocket/core` to add `--packageManager` option
- [x] Update `@ngx-rocket/core` core docs
- [x] Support overriding default package manager through`NGX_PACKAGE_MANAGER` env variable
- [x] Update `generator-ngx-rocket` to use specified package manager
  * update `package.json` scripts and other templates if applicable
  * update console output
- [x] Adapt `updating`, `proxy` and `cordova` guides in consequence
- [x] Add a yarn test case to CI
- [x] Update addons to use specified package manager
- [x] Update `@ngx-rocket/scripts` to use specified package manager, either through the `.yo-rc` file or `NGX_PACKAGE_MANAGER` env var
- [x] Update CLI to use specified package manager, either through the `.yo-rc` file or `NGX_PACKAGE_MANAGER` env var
- [x] Update `generator-ngx-rocket-addon`
- [x] Add warning for cordova projects
- [x] Add documentation on generator option

**Comment by sinedied** [comment]
Note: currently yarn does not play well with Cordova as [npm usage is hardcoded](https://issues.apache.org/jira/browse/CB-12242) in `cordova-lib`. Mixing both npm and yarn in a project is not good, so for now a warning will be emitted when using yarn while generating cordova projects.
